### ISSUE TITLE
infer 함수를 배치 단위로 실행할 수 있는 방법은 없나요?

### ISSUE THREAD

**Issue by sorryhyun** [AIRC-KETI/ke-t5#12]
Downstream models (Tensorflow saved model) 중 ke.newslike ke_t5_nikl_summary_mixture_equal large model을 사용하고 있습니다.
제공해주신 example대로 다음 방법으로 정의를 내리고 있습니다.
```python
        import tensorflow as tf
        import tensorflow_text
        self.model_name = model_name
        loaded = tf.saved_model.load(model_name)
        self.infer = loaded.signatures["serving_default"]
```
signature가 1개의 input만 받도록 만들어져 있던데, 배치 단위로 실행시킬 수 있는 방법은 없을까요? 텐서플로우를 처음 써봐서 잘 모르는점이 많습니다. 죄송합니다.

**Comment by kimsan0622** [comment]
summarization이 필요하시다면, [long-ke-t5](https://github.com/AIRC-KETI/long-ke-t5)에서 공개한 요약 모델을 사용해보시는걸 권장드립니다.

저도 회사 입사하면서 팀원들이 모두 pytorch를 사용하고 있어서 pytorch로 갈아탄지 오래되다보니, tensorflow가 잘 기억이 안나네요... ㅠㅠ

[long-ke-t5](https://github.com/AIRC-KETI/long-ke-t5)에서 요약 모델 사용방법도 같이 적혀있으니 해당 모델을 이용해 보시길 권장 드립니다.
