### ISSUE TITLE
pretrained model의 동일 단어 출력 현상

### ISSUE THREAD

**Issue by woghdwoghd113** [AIRC-KETI/ke-t5#13]
안녕하세요!  멋진 모델을 만들어 주셔서 감사합니다!
저는 현재 올려주신 모델을 통해 번역 테스크를 수행하는 파인튜닝 모델을 생성하려고 합니다 ㅎㅎ 
학습 전, 본래 pretrained 모델의 생성 결과물을 확인해보고자 테스트를 해보니, 
아래 어떤분께서 올려주신 이슈(#1 )와 동일한 결과가 나오는 것을 확인했습니다
다운스트림 테스크 수행을 위해 파인튜닝을 하기 전이더라도 어느정도 시퀀스 생성을 자연스럽게 하는 것이 정상일 것으로 생각되는데...
이게 한 단어만 시퀀스마다 계속 출력하는게 어떤 이유일지... 혹시 생각하고 계신 이유가 있다면 듣고싶어 이렇게 질문 남깁니다!ㅎㅎ
감사합니다.

**Comment by kimsan0622** [comment]
네. 안녕하세요?

일단 ke-t5는 T-5처럼 `span corruption`을 training objective로 하여 학습되었습니다.

`span corruption`은 GPT 계열에서처럼 Next Token Prediction (또는 AutoRegressive objective)이 아니기 때문에 다음 문장을 자연스럽게 생성하지 못합니다.
예를 들어, "pretrained model의 동일 단어 출력 현상" 라는 문장이 있을때, `span corruption`은
"pretrained <special token 1>의 동일 <special token 2> 현상"을 입력으로 줬을때, "<special token 1> model <special token 2> 단어 출력<special token 3> "이 생성되도록 학습됩니다.
즉 빈칸안에 들어갈 말을 생성하도록 학습됩니다.
학습방식만 놓고 봤을때, 파인튜닝을 진행하지 않으면 자연스러운 문장을 생성하지 힘들거 같죠?

따라서 `span corruption`으로 학습된 모델은 파인 튜닝을 안하면 문장 생성이 어렵습니다.
또한 사전 학습간에 입력으로 주어졌던 스페셜 토큰도 주어지지 않았기 때문에 빈칸안에 들어가기 알맞은 말도 생성해내지 못합니다.

추가적으로 말씀드리면 Autoregressive objective로 학습된 모델들도 종종 같은 단어 반복현상이 있습니다. 그래서 문장 생성시 beam search나, 샘플링, 단어 반복 시 패널티, 최대 반복 가능 단어 등의 파라미터로 제어를 하고 있습니다.

입력으로 주어진 문장 중 없어진 문장을 생성하도록 학습한 모델인 [Long ke-t5](https://github.com/AIRC-KETI/long-ke-t5) 공개되어 있습니다.
이 모델은 GPT 계열처럼 다음 단어(다음 문장)을 생성하도록 한것은 아니지만, 문서 중 가장 중요하다고 판단되는 문장들을 제거한 뒤, 이를 입력으로 주고 제거된 문장들을 생성하도록 학습되었기 때문에, 파인튜닝을 하지 않아도 문장을 생성하긴 합니다.

이 모델도 한국어/영어 둘 다 학습되었기 때문에 번역 태스크를 수행할 수 있습니다.

**Comment by woghdwoghd113** [comment]
아 이해하였습니다 ㅎㅎ 많은 도움이 됐습니다 감사합니다!

**Comment by kimsan0622** [comment]
이슈 클로즈하겠습니다.
