### ISSUE TITLE
모델 체크포인트

### ISSUE THREAD

**Issue by sooftware** [AIRC-KETI/ke-t5#6]
허깅페이스 페이지에 있는 KE-T5 모델을 학습하면, 학습이 잘 되지 않습니다.
같은 데이터, 같은 코드로 다른 T5 모델을 학습했을때는 학습이 잘 되는데, KE-T5의 경우에는 전혀 학습이 되지 않는데요.  
혹시 체크포인트가 잘못 업로드 된건 아닌지, 혹은 사용할때 주의사항이 따로 있는지 문의드립니다.

**Comment by kimsan0622** [comment]
흠... 제가 해본 모든 다운스트림 태스크에서는 잘 되었는데요.
딱히 주의사항은 없습니다.

'전혀 학습이 되지 않는다'는 말이 로스가 줄어들지 않는다는 이야긴가요? 아님 결과가 잘 안나온다는 이야기인가요?

아무래도 코드를 봐야 상황을 판단할 수 있을거 같습니다.
모델, 토크나이저 사용하는 부분만 여기에 올려주시면 최대한 확인하도록 노력하겠습니다.

**Comment by sooftware** [comment]
```python
from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer = T5Tokenizer.from_pretrained('KETI-AIR/ke-t5-large')
model = T5ForConditionalGeneration.from_pretrained('KETI-AIR/ke-t5-large')
```

위와 같은 식으로 모델을 로드해서 학습에 사용했습니다.  

<img width="534" alt="image" src="https://user-images.githubusercontent.com/42150335/182638050-e3621602-f01b-47cb-9ed2-249660bf7529.png">

아래 그래프는 같은 코드, 같은 데이터로 학습했을 때, mBART, pko-T5, KE-T5 loss 스케일의 차이입니다.    
loss는 줄어들지만, 앞의 두 모델과 비교하여 loss scale 자체가 매우 크며, 학습이 끝난 후에 실제로 생성을 해보면 의미없는 문자열들만 반복하는 문제가 있습니다.  
  
제가 모델과 토크나이저 로드할 때 잘못 로드한 것일까요?  
다른 몇 분들께도 문의했는데, KE-T5로 학습하면 잘 되지 않았다는 피드백을 들어서 체크포인트가 바뀐건 아닌지, 혹은 사용법이 좀 다른것인지 의구심이 들어 이슈 남겼습니다.

**Comment by kimsan0622** [comment]
흠... 이상없어 보이는데, 이상하군요...

일단 제가 한번 확인해 보겠습니다.
조치는 다음 2개 중 하나가 될것 같습니다.

1. 문제가 발견되었을 경우, 문제 해결한 후 노티
2. 문제가 발견되지 않았을 경우, Github에 간단한 sample 코드 몇개 업로드

**Comment by sooftware** [comment]
네 확인해보겠습니다 감사합니다.
