### ISSUE TITLE
Tokenizer vocab_size

### ISSUE THREAD

**Issue by BonbonKim** [AIRC-KETI/ke-t5#7]
안녕하세요.
좋은 pre-trained model을 공개해주셔서 감사드립니다.
pre-trained model을 직접 다운로드 받아 사용하는 과정에서 문제가 생깁니다.

tokizer_config.json으로 토크나이저를 load해서 확인했을 때, 토크나이저의 vocab_size는 64000이고, 
config.json 내의 vocab_size는 64128으로 되어있습니다.
이 부분에서 vocab_size가 다른 점이 궁금합니다.

predict 과정에서도 아래와 같은 에러가 납니다.
RuntimeError: The size of tensor a (64128) must match the size of tensor b (64000) at non-singleton dimension 1.

**Comment by kimsan0622** [comment]
안녕하세요? 늦은 시간까지 고생하시는걸 보니 공대 석박사 과정이신가 보군요 ^^ (화이팅입니다ㅎㅎ)

먼저, 저도 맨 처음 이 모델을 만들때 같은 의문을 품고 알아봤던 입장으로써 말씀드립니다. 
(제가 틀렸을 수 있으나 적어도 제가 분석한 결과를 토대로 결론을 내린 것이니 틀린 부분이 있다면 동료 연구자로써 피드백 부탁드립니다.)

1. tokenizer의 size는 google sentencepice model vocab size + 100입니다.
이 부분은 huggingface tokenizer의 다음 코드 때문입니다.
```python
def vocab_size(self):
        return self.sp_model.get_piece_size() + self._extra_ids
```

여기서 self.sp_model.get_piece_size()는 sp model size이며 ke-t5는 영어와 한국어 포함 64,000개의 vocab을 만들었기 때문에 이 값은 64,000이 됩니다.
하지만 huggingface model로 변환하는 과정에서 extra_ids 100개가 추가되며 64,100이 됩니다.
따라서 실제로 현재 tokenizer가 동작하는 token id의 범위는 0 - 64,099입니다.
실제로 모델이 사전학습간에 본 토큰들의 범위는 0 ~ 63,999 + 64,000 - ?입니다.
윗줄에서 ?인 이유는 모델 학습에 span corruption을 사용했으며, span 당 64,099부터 1씩 줄어드는 식으로 token을 활용했기 때문에,
최대 몇 토큰들이 마스킹되었는지 증빙할 수 없지만 아마 100 token정도는 사용되었을거라고 추측합니다. 
강렬히? 원하시면 (시간이 된다면!!!) 얼마나 사용되었는지 측정하여 알려드리겠습니다.

PS. 여기서 추가적으로 말씀드리고 싶은것은 최근 ke-t5 모델을 사용하면서 일반 t5모델 (t5, mt5)등과 loss 값과 비교하여 문의를 주시는 분들이 있습니다.
여기서 t5, mt5가 기본 모델로 공개한 것들은 span corruption만 사용한 모델이 아닙니다. 
(t5의 경우 huggingface, gs bucket에 기본 공개한 모델들은 여러 downstream tasks들을 포함한 SSL+supervised generation model이며, mt5의 경우도 비슷합니다. 제 기억상으로 xnli로 기억하고 있습니다.) 
따라서 학습할때, 당연히 span corruption만 사용한 사전학습모델을 이용하여 generation 등과 같은 다운스트림 태스크에 적용할때, 초기 로스가 큽니다. 즉, 하이퍼파라미터 튜닝을 해줘야합니다. T5 논문에 나온 성능들은 다들 span corruption을 이용한 사전 학습모델을 사용한 성능입니다. 논문에서 adafactor optimizer가 괜히 lr 0.001, constanct lr scheduler를 사용한게 아닙니다. t5 논문에 사용한 span corruption model을 사용하려면 gcp bucket가서 따로 tf to pytorch 변환하셔야 합니다. (약 1년전에 업데이트된 지식이므로 지금은 다를 수 있습니다.)

궁금하셨던 부분의 결론을 말씀드리겠습니다.
먼저  T5 tokenizer는 다음 코드 때문에 실제 우리가 설정한 vocab size를 벗어나더라도 전혀 에러가 나지 않습니다.
즉 vocab size 64,128인데, 100,000값을 디코드 해도 에러가 나지 않습니다. 
default값이 spm vocab size를 초과하는 값에 대해서는 extra_ids만큼 거꾸로 할당이 되고, extra_ids가 넘어가면 - 대역으로 넘어가기 때문입니다.
```python
    def _convert_token_to_id(self, token):
        """Converts a token (str) in an id using the vocab."""
        if token.startswith("<extra_id_"):
            match = re.match(r"<extra_id_(\d+)>", token)
            num = int(match.group(1))
            return self.vocab_size - num - 1
        return self.sp_model.piece_to_id(token)

    def _convert_id_to_token(self, index):
        """Converts an index (integer) in a token (str) using the vocab."""
        if index < self.sp_model.get_piece_size():
            token = self.sp_model.IdToPiece(index)
        else:
            token = f"<extra_id_{self.vocab_size - 1 - index}>"
        return token
```


쓸데없는 이야기가 많았네요.
결론적으로 모델의 vocab size가 64,128인 이유는 t5를 mesh tensorflow + TPU로 학습시켰기 때문입니다. (huggingface와는 상관 없습니다.)
mesh tensorflow github의 mesh/mesh_tensorflow/transformer/transformer.py 에서 _round_up_to_multiple을 보시면 아래와 같습니다.
```python
def _round_up_to_multiple(n, divisor):
  return n + -n % divisor
```
이 부분에서 embedding layer의 vocab_dim 값을 수정하는데요. 이 함수 때문에 32,100 -->32,128, 64,100 --> 64,128이 되었던겁니다.
따라서 mesh tensorflow에서 학습한 weights를 huggingface(pytorch)로 변환하는 과정에서 mesh tensorflow의 dim을 유지하는 과정에서 vocab size 불일치가 일어난 것입니다.

결론
1. 실제로 64,100을 넘어가는 토큰들은 사전학습과정에서 본적이 없음.
2. huggingface transformers 구현 상 64,000을 넘어가는 N(>infinity)에 대하여 다운스트림 태스크에서 필요하다면 얼마든지 토큰을 추가할 수 있으며 이 경우에 tokenizer는 그냥 사용하면 되고, model의 경우 model.resize_token_embeddings(vocab_size)를 통하여 embedding vectors 크기 재조정 가능
3. 추가 토큰 없이 tokenizer에서 지원하는  token으로만 학습 진행 시 model.resize_token_embeddings(len(tokenizer))를 통하여 모델 임베딩을 tokenizer에서 지원하는 vocab으로 제한해도 성능 저하 없을 확률이 높음. 이 경우 ke-t5의 경우 64,128 --> 64,100으로 embedding layer 사이즈가 변경 될 것임

**Comment by kimsan0622** [comment]
아, 추가적인 코멘트를 더 드리자면 일반적으로 TPU에서 학습할때에는 input sequence length를 8의 배수로 통일하는편입니다. 또한 NLP를 GPU에서 학습시킬때, 일반적으로 속도향상을 위하여 device 당 batch collate 할 때, dynamic collate(huggingface tokenizer에서 stretegy="longest_first")를 사용하실텐데 TPU에서는 이러한 dynamic collate가 속도가 느리다고 합니다. 이 부분은 TPU와 GPU의 연산 방식 차이로 인해 발생하는 것으로 추측되나, 제가 TPU 연산 방식에 대한 지식 부족으로 정확한 이유를 찾기는 힘듭니다.
단지 [TPU 작동 방식](https://cloud.google.com/tpu/docs/intro-to-tpu?hl=ko)에서 "TPU v3가 단일 프로세서에 128x128 ALU로 이루어진 시스톨릭 배열 2개가 포함"인것 때문인 것으로 추측하고 있습니다.

**Comment by kimsan0622** [comment]
에러를 안나게 하려면

```python
from transformers import AutoTokenizer, T5ForConditionalGeneration, T5Encoder

tokenizer = AutoTokenizer.from_pretrained("KETI-AIR/ke-t5-base")
model = T5ForConditionalGeneration.from_pretrained("KETI-AIR/ke-t5-base")
model = T5Encoder.from_pretrained("KETI-AIR/ke-t5-base")
```
와 같이 사용하시면 됩니다.
만약 custom model을 사용하시고 싶으시면
`T5Model`, `T5Encoder`, `T5ForConditionalGeneration`을 상속받아 클래스를 만드시면 에러없이 잘 동작합니다.
head를 붙이실 거라면 상속받으실 필요없이 뒤에 붙이시면 됩니다.

**Comment by BonbonKim** [comment]
친절한 답변 정말 감사합니다.
kimsan님께서 알려주신 내용 토대로 진행해보겠습니다.

추가로 덧붙여주신 내용들도 감사합니다 ㅎㅎ
좋은 하루 되세요 :)
